server:
  port: 2200
spring:
  jpa:
    database: camunda
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
